# Generated by Django 2.2 on 2019-07-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='losses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
