# Generated by Django 2.2 on 2019-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
